processors:
  metrics:
    blocks_size:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_BlocksSize
    capability_usage:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_CapabilityUsageDuration
    heap_allocated:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_HeapAllocated
    heap_live:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_HeapLive
    heap_prof_sample:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_HeapProfSample
    heap_size:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_HeapSize
    mem_current:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_MemCurrent
    mem_needed:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_MemNeeded
    mem_returned:
      aggregate: by_batch
      description: null
      enabled: true
      name: ghc_eventlog_MemReturned
  spans:
    capability_usage:
      description: null
      enabled: false
      name: ghc_eventlog_CapabilityUsage
    thread_state:
      description: null
      enabled: false
      name: ghc_eventlog_ThreadState
