receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
        # Set the message size limit to 20MiB (default: 4MiB)
        max_recv_msg_size_mib: 20
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed
  otlp/tempo:
    endpoint: "tempo:24317"
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9090"
  otlp/pyroscope:
    endpoint: "pyroscope:4040"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp/loki]
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus]
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/tempo]
    profiles:
      receivers: [otlp]
      exporters: [debug, otlp/pyroscope]
