services:
  grafana:
    # container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: "curl -f http://localhost:3000/api/health"
      interval: 1m
      timeout: 10s
      retries: 5
    volumes:
      - "./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./config/grafana-dashboards-eventlog-heap.json:/var/lib/grafana/dashboards/eventlog-heap.json"
      # - "./config/grafana-dashboards-eventlog-live-aggregation.json:/var/lib/grafana/dashboards/eventlog-live-aggregation.json"
      - "./config/grafana-dashboards-eventlog-threads.json:/var/lib/grafana/dashboards/eventlog-threads.json"
      - "./config/grafana-dashboards-process-overview.json:/var/lib/grafana/dashboards/eventlog-process-overview.json"

  otelcol:
    # container_name: otelcol
    image: otel/opentelemetry-collector-contrib:latest
    depends_on:
      prometheus:
        condition: "service_started"
      tempo:
        condition: "service_started"
    command:
      - "--config=/etc/otelcol/config.yaml"
    volumes:
      - "./config/otelcol.yaml:/etc/otelcol/config.yaml"
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zPages extension

  prometheus:
    # container_name: prometheus
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - "./config/prometheus.yaml:/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090" # Prometheus

  tempo:
    # container_name: tempo
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - "./config/tempo.yaml:/etc/tempo.yaml"
    ports:
      - "24317:24317" # OTLP gRPC receiver
      - "24318:24318" # OTLP HTTP receiver
      - "3200:3200" # Tempo
