services:
  grafana:
    # container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    healthcheck:
      test: "curl -f http://localhost:3000/api/health"
      interval: 1m
      timeout: 10s
      retries: 5
    environment:
      - GF_PLUGINS_PREINSTALL_SYNC=grafana-pyroscope-app
    volumes:
      - "./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml"
      - "./config/grafana-dashboards-eventlog-heap.json:/var/lib/grafana/dashboards/eventlog-heap.json"
      - "./config/grafana-dashboards-eventlog-logs.json:/var/lib/grafana/dashboards/eventlog-logs.json"
      - "./config/grafana-dashboards-eventlog-stack-profile.json:/var/lib/grafana/dashboards/eventlog-stack-profile.json"
      - "./config/grafana-dashboards-eventlog-threads.json:/var/lib/grafana/dashboards/eventlog-threads.json"

  loki:
    # container_name: loki
    image: grafana/loki:latest
    command:
      - "--config.file=/etc/loki/config.yaml"
    ports:
      - "3100"
    volumes:
      - "./config/loki.yaml:/etc/loki/config.yaml"

  otelcol:
    # container_name: otelcol
    image: otel/opentelemetry-collector-contrib:0.140.1

    depends_on:
      loki:
        condition: "service_started"
      prometheus:
        condition: "service_started"
      tempo:
        condition: "service_started"
      pyroscope:
        condition: "service_started"
    command:
      - "--config=/etc/otelcol/config.yaml"
      - "--feature-gates=service.profilesSupport"
    volumes:
      - "./config/otelcol.yaml:/etc/otelcol/config.yaml"
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zPages extension

  prometheus:
    # container_name: prometheus
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - "./config/prometheus.yaml:/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090" # Prometheus

  pyroscope:
    # container_name: pyroscope
    image: grafana/pyroscope:1.16.0
    command:
      - "-config.file=/etc/pyroscope.yaml"
    volumes:
      - "./config/pyroscope.yaml:/etc/pyroscope.yaml"
    ports:
      - 4040:4040 # Pyroscope

  tempo:
    # container_name: tempo
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - "./config/tempo.yaml:/etc/tempo.yaml"
    ports:
      - "24317:24317" # OTLP gRPC receiver
      - "24318:24318" # OTLP HTTP receiver
      - "3200:3200" # Tempo
