processors:
  metrics:
    blocks_size:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_BlocksSize
    capability_usage:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_CapabilityUsageDuration
    heap_allocated:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_HeapAllocated
    heap_live:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_HeapLive
    heap_prof_sample:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_HeapProfSample
    heap_size:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_HeapSize
    mem_current:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_MemCurrent
    mem_needed:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_MemNeeded
    mem_returned:
      aggregate: by_batch
      description: null
      enabled: true
      name: eventlog_live_MemReturned
  spans:
    capability_usage:
      description: null
      enabled: false
      name: eventlog_live_CapabilityUsage
    thread_state:
      description: null
      enabled: false
      name: eventlog_live_ThreadState
