processors:
  metrics:
    blocks_size:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_BlocksSize
    capability_usage:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_CapabilityUsageDuration
    heap_allocated:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_HeapAllocated
    heap_live:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_HeapLive
    heap_prof_sample:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_HeapProfSample
    heap_size:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_HeapSize
    mem_current:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_MemCurrent
    mem_needed:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_MemNeeded
    mem_returned:
      aggregate: by_batch
      description: null
      enabled: true
      name: oddball_MemReturned
  spans:
    capability_usage:
      description: null
      enabled: false
      name: oddball_CapabilityUsage
    thread_state:
      description: null
      enabled: false
      name: oddball_ThreadState
